// <auto-generated />
using System;
using GoogleCalendarManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoogleCalendarManagement.Data.Migrations
{
    [DbContext(typeof(CalendarDbContext))]
    [Migration("20260330201850_HardenGcalEventVersionHistory")]
    partial class HardenGcalEventVersionHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("log_id");

                    b.Property<string>("AffectedDates")
                        .HasColumnType("TEXT")
                        .HasColumnName("affected_dates");

                    b.Property<string>("AffectedEvents")
                        .HasColumnType("TEXT")
                        .HasColumnName("affected_events");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("OperationDetails")
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_details");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_type");

                    b.Property<bool?>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<bool?>("UserAction")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_action");

                    b.HasKey("LogId");

                    b.HasIndex("OperationType")
                        .HasDatabaseName("idx_audit_operation");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_audit_timestamp");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.Config", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigType")
                        .HasColumnType("TEXT")
                        .HasColumnName("config_type");

                    b.Property<string>("ConfigValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("config_value");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("ConfigKey");

                    b.ToTable("config", (string)null);

                    b.HasData(
                        new
                        {
                            ConfigKey = "min_event_duration_minutes",
                            ConfigType = "integer",
                            ConfigValue = "5",
                            Description = "Minimum duration to show events",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ConfigKey = "phone_coalesce_gap_minutes",
                            ConfigType = "integer",
                            ConfigValue = "15",
                            Description = "Max gap for phone coalescing",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ConfigKey = "youtube_coalesce_gap_minutes",
                            ConfigType = "integer",
                            ConfigValue = "30",
                            Description = "Gap after video duration for YouTube",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ConfigKey = "call_min_duration_minutes",
                            ConfigType = "integer",
                            ConfigValue = "3",
                            Description = "Minimum call duration to import",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ConfigKey = "youtube_char_limit_short",
                            ConfigType = "integer",
                            ConfigValue = "40",
                            Description = "Char limit for events <90min",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ConfigKey = "eight_fifteen_threshold",
                            ConfigType = "integer",
                            ConfigValue = "8",
                            Description = "Minutes required in 15-min block",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.DataSourceRefresh", b =>
                {
                    b.Property<int>("RefreshId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("refresh_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("LastRefreshedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_refreshed_at");

                    b.Property<int?>("RecordsFetched")
                        .HasColumnType("INTEGER")
                        .HasColumnName("records_fetched");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_name");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<bool?>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.Property<string>("SyncToken")
                        .HasColumnType("TEXT")
                        .HasColumnName("sync_token");

                    b.HasKey("RefreshId");

                    b.HasIndex("SourceName", "LastRefreshedAt")
                        .HasDatabaseName("idx_refresh_source");

                    b.HasIndex("SourceName", "StartDate", "EndDate")
                        .HasDatabaseName("idx_refresh_date");

                    b.ToTable("data_source_refresh", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.GcalEvent", b =>
                {
                    b.Property<string>("GcalEventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("gcal_event_id");

                    b.Property<bool>("AppCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("app_created");

                    b.Property<DateTime?>("AppLastModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("app_last_modified_at");

                    b.Property<bool>("AppPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("app_published");

                    b.Property<DateTime?>("AppPublishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("app_published_at");

                    b.Property<string>("CalendarId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("calendar_id");

                    b.Property<string>("ColorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("color_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDatetime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_datetime");

                    b.Property<string>("GcalEtag")
                        .HasColumnType("TEXT")
                        .HasColumnName("gcal_etag");

                    b.Property<DateTime?>("GcalUpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("gcal_updated_at");

                    b.Property<bool?>("IsAllDay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_all_day");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRecurringInstance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_recurring_instance");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("RecurringEventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("recurring_event_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_system");

                    b.Property<DateTime?>("StartDatetime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_datetime");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("GcalEventId");

                    b.HasIndex("AppCreated")
                        .HasDatabaseName("idx_gcal_app_created");

                    b.HasIndex("RecurringEventId")
                        .HasDatabaseName("idx_gcal_recurring");

                    b.HasIndex("SourceSystem")
                        .HasDatabaseName("idx_gcal_source");

                    b.HasIndex("StartDatetime", "EndDatetime")
                        .HasDatabaseName("idx_gcal_event_date");

                    b.ToTable("gcal_event", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.GcalEventVersion", b =>
                {
                    b.Property<int>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_id");

                    b.Property<string>("ChangeReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("change_reason");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("changed_by");

                    b.Property<string>("ColorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("color_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDatetime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_datetime");

                    b.Property<string>("GcalEtag")
                        .HasColumnType("TEXT")
                        .HasColumnName("gcal_etag");

                    b.Property<string>("GcalEventId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("gcal_event_id");

                    b.Property<DateTime?>("GcalUpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("gcal_updated_at");

                    b.Property<bool?>("IsAllDay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_all_day");

                    b.Property<bool>("IsRecurringInstance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_recurring_instance");

                    b.Property<string>("RecurringEventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("recurring_event_id");

                    b.Property<DateTime?>("StartDatetime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_datetime");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.HasKey("VersionId");

                    b.HasIndex("GcalEventId", "CreatedAt")
                        .HasDatabaseName("idx_version_event");

                    b.ToTable("gcal_event_version", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.SaveState", b =>
                {
                    b.Property<int>("SaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("save_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("SaveDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("save_description");

                    b.Property<string>("SaveName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("save_name");

                    b.Property<string>("SnapshotData")
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_data");

                    b.HasKey("SaveId");

                    b.ToTable("save_state", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.SystemState", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("state_id");

                    b.Property<string>("StateName")
                        .HasColumnType("TEXT")
                        .HasColumnName("state_name");

                    b.Property<string>("StateValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("state_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("StateId");

                    b.HasIndex("StateName")
                        .IsUnique();

                    b.ToTable("system_state", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.GcalEventVersion", b =>
                {
                    b.HasOne("GoogleCalendarManagement.Data.Entities.GcalEvent", "GcalEvent")
                        .WithMany("Versions")
                        .HasForeignKey("GcalEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GcalEvent");
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.GcalEvent", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
