// <auto-generated />
using GoogleCalendarManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GoogleCalendarManagement.Data.Migrations
{
    [DbContext(typeof(CalendarDbContext))]
    [Migration("20260605021000_DropLegacyCiv5SessionPointTable")]
    partial class DropLegacyCiv5SessionPointTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");
#pragma warning restore 612, 618
        }
    }
}
