// <auto-generated />
using System;
using GoogleCalendarManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoogleCalendarManagement.Data.Migrations
{
    [DbContext(typeof(CalendarDbContext))]
    partial class CalendarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.CallLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CallType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("call_type");

                    b.Property<string>("Contact")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_seconds");

                    b.Property<int>("ImportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("import_id");

                    b.Property<string>("LinkedEventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("linked_event_id");

                    b.Property<string>("LinkedEventType")
                        .HasColumnType("TEXT")
                        .HasColumnName("linked_event_type");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT")
                        .HasColumnName("number");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("service");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("idx_call_log_entry_date");

                    b.HasIndex("Date", "Number", "DurationSeconds")
                        .HasDatabaseName("idx_call_log_entry_dedup");

                    b.HasIndex("ImportId");

                    b.ToTable("call_log_entry", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.CallLogImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateMax")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_max");

                    b.Property<DateOnly>("DateMin")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_min");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("imported_at");

                    b.Property<int>("RecordCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("record_count");

                    b.HasKey("Id");

                    b.ToTable("call_log_import", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("log_id");

                    b.Property<string>("AffectedDates")
                        .HasColumnType("TEXT")
                        .HasColumnName("affected_dates");

                    b.Property<string>("AffectedEvents")
                        .HasColumnType("TEXT")
                        .HasColumnName("affected_events");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("OperationDetails")
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_details");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_type");

                    b.Property<bool?>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<bool?>("UserAction")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_action");

                    b.HasKey("LogId");

                    b.HasIndex("OperationType")
                        .HasDatabaseName("idx_audit_operation");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_audit_timestamp");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.Config", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigType")
                        .HasColumnType("TEXT")
                        .HasColumnName("config_type");

                    b.Property<string>("ConfigValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("config_value");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("ConfigKey");

                    b.ToTable("config", (string)null);

                    b.HasData(
                        new
                        {
                            ConfigKey = "min_event_duration_minutes",
                            ConfigType = "integer",
                            ConfigValue = "5",
                            Description = "Minimum duration to show events",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ConfigKey = "phone_coalesce_gap_minutes",
                            ConfigType = "integer",
                            ConfigValue = "15",
                            Description = "Max gap for phone coalescing",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ConfigKey = "youtube_coalesce_gap_minutes",
                            ConfigType = "integer",
                            ConfigValue = "30",
                            Description = "Gap after video duration for YouTube",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ConfigKey = "call_min_duration_minutes",
                            ConfigType = "integer",
                            ConfigValue = "3",
                            Description = "Minimum call duration to import",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ConfigKey = "youtube_char_limit_short",
                            ConfigType = "integer",
                            ConfigValue = "40",
                            Description = "Char limit for events <90min",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ConfigKey = "eight_fifteen_threshold",
                            ConfigType = "integer",
                            ConfigValue = "8",
                            Description = "Minutes required in 15-min block",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.DataSource", b =>
                {
                    b.Property<int>("DataSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("data_source_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_key");

                    b.Property<bool>("SupportsNoDataHint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("supports_no_data_hint");

                    b.HasKey("DataSourceId");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasDatabaseName("idx_data_source_key");

                    b.ToTable("data_source", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.DataSourceImportLog", b =>
                {
                    b.Property<int>("ImportLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("import_log_id");

                    b.Property<DateOnly>("CoveredEndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("covered_end_date");

                    b.Property<DateOnly>("CoveredStartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("covered_start_date");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("data_source_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("imported_at");

                    b.Property<int?>("RecordsFetched")
                        .HasColumnType("INTEGER")
                        .HasColumnName("records_fetched");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.HasKey("ImportLogId");

                    b.HasIndex("DataSourceId");

                    b.ToTable("data_source_import_log", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.DataSourceRefresh", b =>
                {
                    b.Property<int>("RefreshId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("refresh_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("LastRefreshedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_refreshed_at");

                    b.Property<int?>("RecordsFetched")
                        .HasColumnType("INTEGER")
                        .HasColumnName("records_fetched");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_name");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<bool?>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.Property<string>("SyncToken")
                        .HasColumnType("TEXT")
                        .HasColumnName("sync_token");

                    b.HasKey("RefreshId");

                    b.HasIndex("SourceName", "LastRefreshedAt")
                        .HasDatabaseName("idx_refresh_source");

                    b.HasIndex("SourceName", "StartDate", "EndDate")
                        .HasDatabaseName("idx_refresh_date");

                    b.ToTable("data_source_refresh", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.DateSourceIntegration", b =>
                {
                    b.Property<int>("IntegrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("integration_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("data_source_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<bool>("Integrated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("integrated");

                    b.Property<DateTime?>("IntegratedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("integrated_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("IntegrationId");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("Date", "DataSourceId")
                        .IsUnique()
                        .HasDatabaseName("idx_date_source_integration_date_source");

                    b.ToTable("date_source_integration", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.DeletedEvent", b =>
                {
                    b.Property<string>("GcalEventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("gcal_event_id");

                    b.Property<bool?>("AppCreated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("app_created");

                    b.Property<string>("CalendarId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("calendar_id");

                    b.Property<string>("ColorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("color_id");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletionSource")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("deletion_source");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDatetime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_datetime");

                    b.Property<string>("GcalEtag")
                        .HasColumnType("TEXT")
                        .HasColumnName("gcal_etag");

                    b.Property<bool?>("IsAllDay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_all_day");

                    b.Property<bool?>("IsRecurringInstance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_recurring_instance");

                    b.Property<DateTime?>("OriginalCreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_created_at");

                    b.Property<DateTime?>("OriginalUpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_updated_at");

                    b.Property<string>("RecurringEventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("recurring_event_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_system");

                    b.Property<DateTime?>("StartDatetime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_datetime");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.HasKey("GcalEventId");

                    b.HasIndex("StartDatetime")
                        .HasDatabaseName("idx_deleted_event_date");

                    b.ToTable("deleted_event", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.GcalEvent", b =>
                {
                    b.Property<string>("GcalEventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("gcal_event_id");

                    b.Property<bool>("AppCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("app_created");

                    b.Property<DateTime?>("AppLastModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("app_last_modified_at");

                    b.Property<bool>("AppPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("app_published");

                    b.Property<DateTime?>("AppPublishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("app_published_at");

                    b.Property<string>("CalendarId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("calendar_id");

                    b.Property<string>("ColorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("color_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDatetime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_datetime");

                    b.Property<string>("GcalEtag")
                        .HasColumnType("TEXT")
                        .HasColumnName("gcal_etag");

                    b.Property<DateTime?>("GcalUpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("gcal_updated_at");

                    b.Property<bool?>("IsAllDay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_all_day");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRecurringInstance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_recurring_instance");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("RecurringEventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("recurring_event_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_system");

                    b.Property<DateTime?>("StartDatetime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_datetime");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("GcalEventId");

                    b.HasIndex("AppCreated")
                        .HasDatabaseName("idx_gcal_app_created");

                    b.HasIndex("RecurringEventId")
                        .HasDatabaseName("idx_gcal_recurring");

                    b.HasIndex("SourceSystem")
                        .HasDatabaseName("idx_gcal_source");

                    b.HasIndex("StartDatetime", "EndDatetime")
                        .HasDatabaseName("idx_gcal_event_date");

                    b.HasIndex("StartDatetime", "SourceSystem")
                        .IsUnique()
                        .HasDatabaseName("idx_gcal_event_day_name_unique")
                        .HasFilter("source_system = 'day_name' AND is_deleted = 0");

                    b.ToTable("gcal_event", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.GcalEventVersion", b =>
                {
                    b.Property<int>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_id");

                    b.Property<string>("ChangeReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("change_reason");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("changed_by");

                    b.Property<string>("ColorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("color_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDatetime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_datetime");

                    b.Property<string>("GcalEtag")
                        .HasColumnType("TEXT")
                        .HasColumnName("gcal_etag");

                    b.Property<string>("GcalEventId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("gcal_event_id");

                    b.Property<DateTime?>("GcalUpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("gcal_updated_at");

                    b.Property<bool?>("IsAllDay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_all_day");

                    b.Property<bool>("IsRecurringInstance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_recurring_instance");

                    b.Property<string>("RecurringEventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("recurring_event_id");

                    b.Property<DateTime?>("StartDatetime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_datetime");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.HasKey("VersionId");

                    b.HasIndex("GcalEventId", "CreatedAt")
                        .HasDatabaseName("idx_version_event");

                    b.ToTable("gcal_event_version", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.PendingEvent", b =>
                {
                    b.Property<string>("PendingEventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("pending_event_id");

                    b.Property<bool>("AppCreated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("app_created");

                    b.Property<string>("CalendarId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("calendar_id");

                    b.Property<string>("ColorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("color_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDatetime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_datetime");

                    b.Property<string>("GcalEventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("gcal_event_id");

                    b.Property<bool?>("IsAllDay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_all_day");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("edit")
                        .HasColumnName("operation_type");

                    b.Property<DateTime?>("PublishAttemptedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("publish_attempted_at");

                    b.Property<string>("PublishError")
                        .HasColumnType("TEXT")
                        .HasColumnName("publish_error");

                    b.Property<bool>("ReadyToPublish")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ready_to_publish");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_system");

                    b.Property<DateTime?>("StartDatetime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_datetime");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("PendingEventId");

                    b.HasIndex("GcalEventId")
                        .IsUnique()
                        .HasDatabaseName("idx_pending_event_gcal_event_id");

                    b.HasIndex("StartDatetime", "EndDatetime")
                        .HasDatabaseName("idx_pending_event_date");

                    b.HasIndex("StartDatetime", "SourceSystem")
                        .IsUnique()
                        .HasDatabaseName("idx_pending_event_day_name_unique")
                        .HasFilter("source_system = 'day_name'");

                    b.ToTable("pending_event", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.RecurringEventSeries", b =>
                {
                    b.Property<string>("SeriesId")
                        .HasColumnType("TEXT")
                        .HasColumnName("series_id");

                    b.Property<string>("CalendarId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("calendar_id");

                    b.Property<string>("ColorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("color_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("GcalEtag")
                        .HasColumnType("TEXT")
                        .HasColumnName("gcal_etag");

                    b.Property<DateTime?>("GcalUpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("gcal_updated_at");

                    b.Property<bool?>("IsAllDay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_all_day");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Recurrence")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recurrence");

                    b.Property<DateTime?>("SeriesEndDatetime")
                        .HasColumnType("TEXT")
                        .HasColumnName("series_end_datetime");

                    b.Property<DateTime?>("SeriesStartDatetime")
                        .HasColumnType("TEXT")
                        .HasColumnName("series_start_datetime");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("SeriesId");

                    b.ToTable("recurring_event_series", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.SaveState", b =>
                {
                    b.Property<int>("SaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("save_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("SaveDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("save_description");

                    b.Property<string>("SaveName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("save_name");

                    b.Property<string>("SnapshotData")
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_data");

                    b.HasKey("SaveId");

                    b.ToTable("save_state", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.SpotifyStream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AlbumName")
                        .HasColumnType("TEXT")
                        .HasColumnName("album_name");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("artist_name");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<int>("MsPlayed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ms_played");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("played_at");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("track_name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PlayedAt", "TrackName" }, "idx_spotify_data_dedup")
                        .IsUnique();

                    b.HasIndex("PlayedAt")
                        .HasDatabaseName("idx_spotify_data_played_at");

                    b.ToTable("spotify_data", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.SystemState", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("state_id");

                    b.Property<string>("StateName")
                        .HasColumnType("TEXT")
                        .HasColumnName("state_name");

                    b.Property<string>("StateValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("state_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("StateId");

                    b.HasIndex("StateName")
                        .IsUnique();

                    b.ToTable("system_state", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.TogglEntry", b =>
                {
                    b.Property<long>("TogglId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("toggl_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_seconds");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("LinkedEventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("linked_event_id");

                    b.Property<string>("LinkedEventType")
                        .HasColumnType("TEXT")
                        .HasColumnName("linked_event_type");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_name");

                    b.Property<string>("PublishedGcalEventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("published_gcal_event_id");

                    b.Property<bool>("PublishedToGcal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("published_to_gcal");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("TogglDataType")
                        .HasColumnType("TEXT")
                        .HasColumnName("toggl_data_type");

                    b.Property<bool>("VisibleAsEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("visible_as_event");

                    b.HasKey("TogglId");

                    b.HasIndex("Description")
                        .HasDatabaseName("idx_toggl_description");

                    b.HasIndex("PublishedGcalEventId");

                    b.HasIndex("StartTime", "EndTime")
                        .HasDatabaseName("idx_toggl_date");

                    b.HasIndex("TogglDataType")
                        .HasDatabaseName("idx_toggl_type");

                    b.ToTable("toggl_data", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.TogglSleepQuality", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<int?>("Quality")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Date");

                    b.ToTable("toggl_sleep_quality", t =>
                        {
                            t.HasCheckConstraint("CK_toggl_sleep_quality_quality_range", "quality IS NULL OR (quality >= 0 AND quality <= 10)");
                        });
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.TogglPhoneRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("DateFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_from");

                    b.Property<DateOnly?>("DateTo")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_to");

                    b.Property<string>("DescriptionPattern")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description_pattern");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxDurationMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_duration_minutes");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.ToTable("toggl_phone_rule", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.MapsTimelineRaw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("imported_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size_bytes");

                    b.Property<DateOnly?>("CoveredDateMin")
                        .HasColumnType("TEXT")
                        .HasColumnName("covered_date_min");

                    b.Property<DateOnly?>("CoveredDateMax")
                        .HasColumnType("TEXT")
                        .HasColumnName("covered_date_max");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_json");

                    b.HasKey("Id");

                    b.ToTable("maps_timeline_raw", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.Civ5SessionPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("scanned_at");

                    b.Property<DateTime>("FileModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_modified_at");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("game_mode");

                    b.Property<string>("LinkedEventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("linked_event_id");

                    b.Property<string>("LinkedEventType")
                        .HasColumnType("TEXT")
                        .HasColumnName("linked_event_type");

                    b.HasKey("Id");

                    b.HasIndex("FileModifiedAt", "GameMode")
                        .IsUnique()
                        .HasDatabaseName("idx_civ5_data_dedup");

                    b.HasIndex("FileModifiedAt")
                        .HasDatabaseName("idx_civ5_data_file_modified_at");

                    b.ToTable("civ5_data", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.ComfyUIFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_path");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at");

                    b.HasKey("Id");

                    b.HasIndex("FolderPath")
                        .IsUnique()
                        .HasDatabaseName("idx_comfyui_folder_path");

                    b.ToTable("comfyui_folder", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.ComfyUIScanPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("scanned_at");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<string>("LinkedEventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("linked_event_id");

                    b.Property<string>("LinkedEventType")
                        .HasColumnType("TEXT")
                        .HasColumnName("linked_event_type");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_comfyui_data_timestamp");

                    b.HasIndex("Timestamp", "EventType")
                        .IsUnique()
                        .HasDatabaseName("idx_comfyui_data_dedup");

                    b.ToTable("comfyui_data", (string)null);
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.CallLogEntry", b =>
                {
                    b.HasOne("GoogleCalendarManagement.Data.Entities.CallLogImport", "Import")
                        .WithMany("Entries")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Import");
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.DataSourceImportLog", b =>
                {
                    b.HasOne("GoogleCalendarManagement.Data.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.DateSourceIntegration", b =>
                {
                    b.HasOne("GoogleCalendarManagement.Data.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.GcalEventVersion", b =>
                {
                    b.HasOne("GoogleCalendarManagement.Data.Entities.GcalEvent", "GcalEvent")
                        .WithMany("Versions")
                        .HasForeignKey("GcalEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GcalEvent");
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.PendingEvent", b =>
                {
                    b.HasOne("GoogleCalendarManagement.Data.Entities.GcalEvent", "GcalEvent")
                        .WithOne("PendingEvent")
                        .HasForeignKey("GoogleCalendarManagement.Data.Entities.PendingEvent", "GcalEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GcalEvent");
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.TogglEntry", b =>
                {
                    b.HasOne("GoogleCalendarManagement.Data.Entities.GcalEvent", "PublishedGcalEvent")
                        .WithMany()
                        .HasForeignKey("PublishedGcalEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PublishedGcalEvent");
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.CallLogImport", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("GoogleCalendarManagement.Data.Entities.GcalEvent", b =>
                {
                    b.Navigation("PendingEvent");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
