namespace GoogleCalendarManagement.Models;

public sealed record WeekTimedEventLayoutItem(
    string EventId,
    string Title,
    string PrimaryText,
    string? SecondaryText,
    string TooltipText,
    string ColorHex,
    CalendarEventSourceKind SourceKind,
    DateTime StartLocal,
    DateTime EndLocal,
    int DayOffset,
    int GridRow,
    int GridRowSpan,
    double Left,
    double Top,
    double Width,
    double Height,
    double CompactTopPadding,
    bool IsCompact,
    bool UseOverlapOutline,
    int MaxTitleLines,
    double Opacity = 1.0,
    bool IsPendingDelete = false);
